testCases=GetHeaderValue|ParseCseq
test-all:
	go test -v -cover ./...
cover:
	go test -v -coverprofile=cover.out ./...
	go tool cover -html=cover.out -o cover.html
test:
	go test -v -run="$(testCases)" ./...
